trigger:
  branches:
    include:
    - main
    - releases/ebook-*
  paths:
    exclude:
    - CHANGELOG.md
    - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:

  - script: npm ci
    displayName: 'Install'

  - script: npm run build
    displayName: 'Build'


  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
    displayName: 'Create file archive to publish'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish files to Azure Pipelines'
